slightly nicer

diff --git a/grafana-setup b/grafana-setup
--- a/grafana-setup
+++ b/grafana-setup
@@ -3,11 +3,16 @@
 dataSources=$(curl -s 'http://admin:admin@localhost:3000/api/datasources')
 
 if [[ "$dataSources" = "[]" ]]; then
-    echo "Unconfigured, adding a datasource"
+    echo -n "Unconfigured, adding a datasource.."
 
-    curl 'http://admin:admin@localhost:3000/api/datasources' \
+    curl -s 'http://admin:admin@localhost:3000/api/datasources' \
          -X POST \
          -H 'Content-Type: application/json;charset=UTF-8' \
-         --data-binary '{"name":"influx","type":"influxdb","url":"http://localhost:8086","access":"proxy","isDefault":true,"database":"mydb","user":"admin","password":"admin"}'
+         --data-binary '{"name":"influx","type":"influxdb","url":"http://localhost:8086","access":"proxy","isDefault":true,"database":"mydb","user":"admin","password":"admin"}' > /dev/null 2>&1
+    if [[ "$?" -eq 0 ]]; then
+        echo "success."
+    else
+        echo "failed."
+    fi
 
 fi
